# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'visafe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'SDWebImage'
  pod 'DACircularProgress'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'GoogleSignIn'
  pod 'SwiftyUserDefaults'
  pod 'SideMenuSwift'
  pod 'SVPinView'
  pod "ESTabBarController-swift"
  pod 'MXSegmentedPager'

end
